### ISSUE TITLE
Can arduino UNO contact Hololens with BLE

### ISSUE THREAD

**Issue by Marshall-Hu** [FlipWebApps/HololensGPS#1]
I am sorry to write here to contact.  I just need to send message which UNO get to Hololens. But It seems doesnt work in arduino.

**Comment by FlipWebApps** [comment]
Hi. Afraid that I haven't looked into Arduino. I guess the UWA / Hololens part should work (given they use standard BLE) but the client part would need a rewrite. Afraid that I don't have experience with Arduino though to test this, but if you find a solution and want to add it here then just let me know.
